export const GET_MESSAGES = "GET_MESSAGES"
export const ADD_MESSAGE = "ADD_MESSAGE"
export const GET_CHANNELS = "GET_CHANNELS"
export const ADD_CHANNEL = "ADD_CHANNEL"
export const UPLOAD_FILE = "UPLOAD_FILE"